CREATE DATABASE DOJO_24_09_2021
 
 USE DOJO_24_09_2021


CREATE SEQUENCE [dbo].[person_counter] 
 AS [int]
 START WITH 0
 INCREMENT BY 1
 MINVALUE -2147483648
 MAXVALUE 2147483647
 CACHE 
GO

CREATE TABLE [dbo].[PERSON](
	[ID] [int] NOT NULL,
	[NAME] [nvarchar](255) NULL,
	[SURNAME] [nvarchar](255) NULL,
	[DATEOFBIRTH] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PERSON] ADD  DEFAULT (NEXT VALUE FOR [person_counter]) FOR [ID]
GO

